# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /homes/bchenba/OSORT_SIM_TEST

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /homes/bchenba/OSORT_SIM_TEST

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /homes/bchenba/OSORT_SIM_TEST/CMakeFiles /homes/bchenba/OSORT_SIM_TEST/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /homes/bchenba/OSORT_SIM_TEST/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named oq

# Build rule for target.
oq: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 oq
.PHONY : oq

# fast build rule for target.
oq/fast:
	$(MAKE) -f CMakeFiles/oq.dir/build.make CMakeFiles/oq.dir/build
.PHONY : oq/fast

# target to build an object file
enc.o:
	$(MAKE) -f CMakeFiles/oq.dir/build.make CMakeFiles/oq.dir/enc.o
.PHONY : enc.o

# target to preprocess a source file
enc.i:
	$(MAKE) -f CMakeFiles/oq.dir/build.make CMakeFiles/oq.dir/enc.i
.PHONY : enc.i

# target to generate assembly for a file
enc.s:
	$(MAKE) -f CMakeFiles/oq.dir/build.make CMakeFiles/oq.dir/enc.s
.PHONY : enc.s

# target to build an object file
include/bucket.o:
	$(MAKE) -f CMakeFiles/oq.dir/build.make CMakeFiles/oq.dir/include/bucket.o
.PHONY : include/bucket.o

# target to preprocess a source file
include/bucket.i:
	$(MAKE) -f CMakeFiles/oq.dir/build.make CMakeFiles/oq.dir/include/bucket.i
.PHONY : include/bucket.i

# target to generate assembly for a file
include/bucket.s:
	$(MAKE) -f CMakeFiles/oq.dir/build.make CMakeFiles/oq.dir/include/bucket.s
.PHONY : include/bucket.s

# target to build an object file
include/common.o:
	$(MAKE) -f CMakeFiles/oq.dir/build.make CMakeFiles/oq.dir/include/common.o
.PHONY : include/common.o

# target to preprocess a source file
include/common.i:
	$(MAKE) -f CMakeFiles/oq.dir/build.make CMakeFiles/oq.dir/include/common.i
.PHONY : include/common.i

# target to generate assembly for a file
include/common.s:
	$(MAKE) -f CMakeFiles/oq.dir/build.make CMakeFiles/oq.dir/include/common.s
.PHONY : include/common.s

# target to build an object file
include/merge.o:
	$(MAKE) -f CMakeFiles/oq.dir/build.make CMakeFiles/oq.dir/include/merge.o
.PHONY : include/merge.o

# target to preprocess a source file
include/merge.i:
	$(MAKE) -f CMakeFiles/oq.dir/build.make CMakeFiles/oq.dir/include/merge.i
.PHONY : include/merge.i

# target to generate assembly for a file
include/merge.s:
	$(MAKE) -f CMakeFiles/oq.dir/build.make CMakeFiles/oq.dir/include/merge.s
.PHONY : include/merge.s

# target to build an object file
include/oq.o:
	$(MAKE) -f CMakeFiles/oq.dir/build.make CMakeFiles/oq.dir/include/oq.o
.PHONY : include/oq.o

# target to preprocess a source file
include/oq.i:
	$(MAKE) -f CMakeFiles/oq.dir/build.make CMakeFiles/oq.dir/include/oq.i
.PHONY : include/oq.i

# target to generate assembly for a file
include/oq.s:
	$(MAKE) -f CMakeFiles/oq.dir/build.make CMakeFiles/oq.dir/include/oq.s
.PHONY : include/oq.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... oq"
	@echo "... rebuild_cache"
	@echo "... enc.o"
	@echo "... enc.i"
	@echo "... enc.s"
	@echo "... include/bucket.o"
	@echo "... include/bucket.i"
	@echo "... include/bucket.s"
	@echo "... include/common.o"
	@echo "... include/common.i"
	@echo "... include/common.s"
	@echo "... include/merge.o"
	@echo "... include/merge.i"
	@echo "... include/merge.s"
	@echo "... include/oq.o"
	@echo "... include/oq.i"
	@echo "... include/oq.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

